name: Build Installer

on:
  push:
    branches: 
      - main
      - 'release-*'
      - 'beta-release-*'

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}

jobs:
  windows-build:
    name: Build the Ziti Desktop Edge for Windows Installer Package
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@main
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'
          run: |
            npm install
            npm run make
      - name: Upload Window installer
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdge-Win-${{ env.VERSION }}
          path: "out/make/squirrel.windows/x64/ZitiDesktopEdge-*.exe"
  linux-build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@main
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'
          run: |
            npm install 
            npm run make
      - name: Upload Linux Deb installer
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdge-Deb-${{ env.VERSION }}
          path: "out/make/deb/x64/ZitiDesktopEdge-*.deb"
      - name: Upload Linux Rpm installer
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdge-Rpm-${{ env.VERSION }}
          path: "out/make/rpm/x64/ZitiDesktopEdge-*.rpm"