name: Build Installer

on:
  push:
    branches: 
      - main

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}

jobs:
  windows-build:
    name: Build the Ziti Desktop Edge for Windows Installer Package
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src
    steps: 
      - uses: actions/checkout@main
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'
      - run: npm install
      - run: npm i -g electron-packager
      - run: electron-packager ./ Ziti-Desktop-Edge --overwrite --asar --electron-version=21.4.3 --platform=win32 --arch=x64 --prune=true --out=release-builds --icon=./app.ico
  linux-build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps: 
      - uses: actions/checkout@main
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'
      - run: VERSION=$(cat ../version)
      - run: npm install
      - run: npm i -g electron-builder
      - run: electron-builder --linux deb rpm
      - name: Upload Linux Deb installer
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdge-Deb-$VERSION
          path: "dist/ziti-desktop-edge-$VERSION.deb"
      - name: Upload Linux Rpm installer
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdge-Rpm-$VERSION
          path: "dist/ziti-desktop-edge-$VERSION.rpm"