name: Build Installer

on:
  push:
    branches: 
      - main

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}

jobs:
  windows-build:
    name: Build the Ziti Desktop Edge for Windows Installer Package
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src
    steps: 
      - uses: actions/checkout@main
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'
      - run: npm install
      - run: npm i -g electron-packager
      - run: electron-packager ./ Ziti-Desktop-Edge --overwrite --asar --electron-version=21.4.3 --platform=win32 --arch=x64 --prune=true --out=release-builds --icon=./app.ico
  linux-build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps: 
      - uses: actions/checkout@main
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'
      - uses: pCYSl5EDgo/cat@master
        id: vars
        with:
          path: ./version
      - run: echo ${{ steps.vars.outputs.text }}
        env:
          APPVER: ${{ steps.vars.outputs.text }}
      - name: Show Version
        run: echo $APPVER
      - run: npm install
      - run: npm i -g electron-builder
      - run: electron-builder --linux deb rpm
      - name: Upload Linux Deb installer
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdge-Deb-${{ steps.vars.outputs.text }}
          path: "./dist/ziti-desktop-edge-${{ steps.vars.outputs.text }}.deb"
      - name: Upload Linux Rpm installer
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdge-Rpm-${{ steps.vars.outputs.text }}
          path: "./dist/ziti-desktop-edge-${{ steps.vars.outputs.text }}.rpm"